added login route
SchoolHeroes/school-heroes-backend pull request #4
Opened 2024-11-22 17:33 UTC by RoMan-robots

2024-11-22 17:49 UTC, SchoolHeroes reviewed
подумай, як зробити, щоб вся логіка була у контролерах. А у роутах тільки короткі записи в один рядок
router.post("/login", validateBody(schemas.loginSchema), ctrl.login);
міделвару для перевірки тіла запиту додам

2024-11-24 12:40 UTC, DmytroTy requested changes

2024-11-24 12:40 UTC, DmytroTy commented on README.md
> -2. Перемістіться в папку school-heroes-backend
Якщо вже виправляти то й у 15-му рядку не Move а Go

2024-11-24 12:40 UTC, DmytroTy commented on controllers/auth.js
> +}
І що цей код робить?
Май на увазі що недописаний код не комітять, а тим паче в пулл-реквест таке відправляти

2024-11-24 12:40 UTC, DmytroTy commented on middlewares/validateData.js
> +    }
Дуже не оптимальний підхід, тут же можна простіше і ефективніше - перевірити що є і викликати тільки необхідну функцію

2024-11-24 12:40 UTC, DmytroTy commented on controllers/auth.js
> +};
Червоний значок означає відсутність необхідного пустого рядка в кінці файлу

2024-11-24 12:40 UTC, DmytroTy commented on routes/api/auth.js
> +router.post('/login', validateLoginDataMiddleware, (req, res) => res.status(200).json({ message: "Login successful" }));
Так же не можна робити: перевірити валідність даних з допомогою joi, а далі вся логіка в контролері; й не можна всім відповідати 200; та й клієнт очікує не повідомлення 200, а JWT-токен який зможе використовувати

2024-11-26 17:01 UTC, RoMan-robots commented on controllers/auth.js
> +}
Микола попросив зробити пул реквест подивитись, + моє завдання було без самої логіки перевірки

2024-11-26 17:02 UTC, RoMan-robots commented on controllers/auth.js
> +};
у мене його нема

2024-11-26 17:02 UTC, RoMan-robots commented on middlewares/validateData.js
> +    }
ну як мінімум це краще ніж перевіряти через if кожен варіант, а інші я пробував заплутані

2024-11-26 17:05 UTC, RoMan-robots commented on routes/api/auth.js
> +router.post('/login', validateLoginDataMiddleware, (req, res) => res.status(200).json({ message: "Login successful" }));
для галочки треба 200 краще і потім у json скинути жвт, і щоб його здобути треба логіка в контролері якої у нас нема

2024-11-26 17:06 UTC, RoMan-robots commented on routes/api/auth.js
> +router.post('/login', validateLoginDataMiddleware, (req, res) => res.status(200).json({ message: "Login successful" }));
з joi не працював тому я зробив перевірку в контролері для кожного способу свої дані

2024-11-29 19:29 UTC, DmytroTy commented on middlewares/validateData.js
> +    }
Якраз краще відразу перевірити за наявними даними ніж виконувати хтозна скільки ще й заплутавши на додачу

2024-11-29 19:29 UTC, DmytroTy commented on routes/api/auth.js
> +router.post('/login', validateLoginDataMiddleware, (req, res) => res.status(200).json({ message: "Login successful" }));
Після відправки response вже більш нічого не можна відправити - не дозволяє протокол hhtp

2024-12-05 19:58 UTC, closed without merging